Fix bug of key not set for enumeration literal
LionWeb-io/lionweb-java pull request #164
Opened 2024-09-30 13:39 UTC by Ulyana-F1re

Enumeration literal is a separate case in `importEPackage`. Setting the key for it was forgotten.

2024-09-30 13:42 UTC, dslmeinte requested changes
I know that existing unit tests are kind-of shallow, but you could expand an existing one specifically for keys (and possibly IDs) here: https://github.com/LionWeb-io/lionweb-java/blob/master/emf/src/test/java/io/lionweb/lioncore/java/emf/EMFMetamodelImporterTest.java#L169

2024-10-02 10:56 UTC, dslmeinte approved these changes

2024-10-08 08:45 UTC, ftomassetti commented
The PR has been approved. @Ulyana-F1re is it ok if I press the merge button and do a release?

2024-10-08 08:56 UTC, Ulyana-F1re commented
> The PR has been approved. @Ulyana-F1re, is it okay if I press the merge button and make a release?

@ftomassetti yes please. I don't have access to the merge button :)

2024-10-08 08:57 UTC, merged

2024-10-08 10:15 UTC, ftomassetti commented
@Ulyana-F1re a new version has been released. Thank you!